# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Entity',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('hid', models.IntegerField(blank=False, null=False)),
                ('Review_Date', models.CharField(max_length=15)),
                ('Reviewer_Nationality', models.CharField(max_length=50)),
                ('Positive_Review', models.TextField(max_length=2000)),
                ('Negative_Review', models.TextField(max_length=2000)),
                ('Review_Total_Positive_Word_Counts', models.IntegerField(blank=True, null=True)),
                ('Review_Total_Negative_Word_Counts', models.IntegerField(blank=True, null=True)),
                ('Total_Number_of_Reviews_Reviewer_Has_Given', models.IntegerField(blank=True, null=True)),
                ('Reviewer_Score', models.FloatField(blank=True, null=True)),
                ('Tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
