# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Entity',
            fields=[
                ('Hotel_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Hotel_Address', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('Average_Score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('Total_Number_of_Reviews', models.IntegerField(blank=True, null=True)),
                ('Additional_Number_of_Scoring', models.IntegerField(blank=True, null=True)),
                ('hid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='review_entity',
            name='Reviewer_Score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='review_entity',
            name='hid',
            field=models.IntegerField(null=True),
        ),
    ]
