# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171115_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_entity',
            name='hid',
            field=models.IntegerField(null=True),
        ),
    ]
