# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171115_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_entity',
            name='hid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Hotel_Entity'),
        ),
    ]
